name: "factpages-graphview"
services:
  neo4j:
    image: neo4j:community
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
      - ./scripts:/scripts

  db-init:
    image: python:3.13-slim
    depends_on:
      - neo4j
    volumes:
      - ./csvs:/data/csvs
      - ./scripts:/scripts

    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - INIT_FLAG_FILE=/data/.db_initialized
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
    command: ["bash", "/scripts/entrypoint.sh"]
    restart: "no"
